package com.lordjoe.resource_guide;

import com.lordjoe.resource_guide.util.URLValidator;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * com.lordjoe.resource_guide.CheckURLValidation
 * User: Steve
 * Date: 4/27/25
 */
public class CheckURLValidation {
    
    public static final String[] GOOD_URLS ={
        "https://kingcounty.gov/depts/community-human-services/adult-services/older-adults-caregivers/senior-hubs.aspx",
                "https://www.klinegalland.org/care-options/kline-galland-home/",
                "https://www.oldfriendsclub.org",
                "https://www.providence.org/locations/wa/elderplace-redmond?ls=location&y_source=1_MTUwMTY2NzctNzE1LWxvY2F0aW9uLndlYnNpdGU%3D",
                "https://www.evergreenhealthcare.org/access",
                "https://www.nadsa.org",
                "https://www.leadingagewa.org/members/adult-day",
                "https://ccsww.org/services/anchor-south-king-co-shelter-system",
                "https://apichaya.org",
                "https://armsaroundyou.org/what-we-do",
                "https://acrs.org",
                "https://acrs.org/services/employment-and-training-services",
                "https://acrs.org/services/aging-services-for-older-adults/acrs-food-bank",
                "https://atlanticstreetcenter.org",
                "https://atlanticstreetcenter.org",
                "https://atlanticstreetcenter.org",
                "https://auroracommons.org",
                "https://ballardfoodbank.org",
                "https://bellwetherhousing.org",
                "https://benefitslawcenter.org",
                "https://churchbcc.org/missions/localmissions",
                "https://compasshousingalliance.org/emergency-programs/blaine-center",
                "https://blessed-sacrament.org/outreach",
                "https://breadoflifemission.org/emergency-services-overview",
                "https://bridgemin.org/get-equipment",
                "https://byrdbarrplace.org",
                "https://casa-latina.org",
                "https://chiefseattleclub.org",
                "https://cisc-seattle.org/programs/family-support",
                "https://seattle.gov/humanservices/services-and-programs/utility-discount-  program",
                "https://columbialegal.org",
                "https://kingcounty.gov/depts/health/locations/health-insurance/access-and-  outreach/community-health-access-program.aspx",
                "https://compasshousingalliance.org/emergency- programs/compasscenternavigation",
                "https://compasshousingalliance.org/affordable-housing/veterans-center- shoreline",
                "https://seattle.gov/tech",
                "https://disabilityempowerment.org",
                "https://kcdrc.org",
                "https://dfsseattle.org",
                "https://seattle.gov/education/for-parents/child-care-and-preschool/early- childhood-education-and-assistance-program",
                "https://entrehermanos.org",
                "https://expresscu.org",
                "https://freedomprojectwa.org/credible-allies-program",
                "https://friendsofyouth.org/services",
                "https://givinggiftsofhope.org/about",
                "https://hoas.org",
                "https://seattle.ikron.org",
                "https://icsseattle.org",
                "https://ingersollgendercenter.org",
                "https://interactiontransition.org",
                "https://ichs.com",
                "https://ichs.com",
                "https://rescue.org/seattle",
                "https://seattle.gov/tech/services/internet-access",
                "https://compasshousingalliance.org/emergency-programs/janpetersplace",
                "https://jwcenter.org",
                "https://kawabehouse.org",
                "https://kcba.org/For-the-Public/Free-Legal-Assistance/Neighborhood-Legal-  Clinics",
                "https://kcba.org/For-the-Public/Free-Legal-Assistance",
                "https://kcba.org/For-the-Public/Free-Legal-Assistance/The-Records-Project",
                "https://kingcounty.gov/depts/health/locations/columbia.aspx",
                "https://kingcounty.gov/depts/public-defense.aspx",
                "https://kingcounty.gov/depts/health/locations/downtown.aspx",
                "https://kcha.org",
                "https://kingcounty.gov/depts/health/locations/health- insurance/coverage/enrollment-assistance/ORCA-LIFT-card.aspx",
                "https://kingcounty.gov/en/dept/metro/fares-and-payment/discounted-  fares/regional-reduced-fare-permit",
                "https://kingcounty.gov/depts/health/communicable-diseases/hiv-  std/patients/drug-use-harm-reduction/needle-exchange.aspx",
                "https://kingcounty.gov/en/dept/dph/health-safety/health-centers-programs-  services/public-health-centers/north-seattle",
                "https://kingcounty.gov/en/dept/dph/health-safety/health-centers-programs-  services/public-health-centers/white-center",
                "https://kingcounty.gov/depts/community-human-services/veterans/programs-  services.aspx",
                "https://lihihousing.org/villages",
                "https://seattle.gov/tech/internet-and-devices/discounted-computers-and- phones",
                "https://lihihousing.org/housing",
                "https://mapsredmond.org/mcrc",
                "https://mothernation.org/introduction",
                "https://neighborcare.org/georgetown",
                "https://neighborcare.org/high-point",
                "https://neighborcare.org/meridian",
                "https://neighborcare.org/rainier-beach",
                "https://seattlereconomy.org/nestl",
                "https://oxfordhouse.org",
                "https://pmsc-fb.org",
                "https://plannedparenthood.org/health- center/washington/seattle/98122/central-district-health-center-3309-91810",
                "https://plannedparenthood.org/health- center/washington/seattle/98133/northgate-health-center-3975-91810",
                "https://plannedparenthood.org/health- center/washington/seattle/98105/university-district-health-center-2532-91810",
                "https://plannedparenthood.org/health-center/washington/seattle/98106/white-  center-health-center-4161-91810",
                "https://plymouthhousing.org",
                "https://pocaan.org/curb",
                "https://porchlightcares.org",
                "https://praisealujah.org/discipleship-training",
                "https://qlawfoundation.org/legal-clinics",
                "https://realchangenews.org",
                "https://restsurvivors.org/services/overview",
                "https://kcrha.org/regional-access-points",
                "https://seattle.salvationarmy.org/seattle_services/domestic-violence-programs- and-shelters",
                "https://parkways.seattle.gov/2020/03/16/seattle-parks-and-recreations-free-  shower-program-operating-on-modified-schedule-at-5-community-centers",
                "https://parkways.seattle.gov/2020/03/16/seattle-parks-and-recreations-free-  shower-program-operating-on-modified-schedule-at-5-community-centers",
                "https://parkways.seattle.gov/2020/03/16/seattle-parks-and-recreations-free-  shower-program-operating-on-modified-schedule-at-5-community-centers",
                "https://parkways.seattle.gov/2020/03/16/seattle-parks-and-recreations-free-  shower-program-operating-on-modified-schedule-at-5-community-centers",
                "https://parkways.seattle.gov/2020/03/16/seattle-parks-and-recreations-free-  shower-program-operating-on-modified-schedule-at-5-community-centers",
                "https://spl.org/programs-and-services/civics-and-social-services/immigrant-and-  refugee-services",
                "https://spl.org/programs-and-services/civics-and-social-services/job-resources",
                "https://spl.org/programs-and-services/civics-and-social-services/resources-for-  the-formerly-incarcerated",
                "https://spl.org/programs-and-services/civics-and-social-services/social-services-  referrals",
                "https://oslserves.org",
                "https://ugm.org",
                "https://va.gov/seattle-vet-center",
                "https://seattlereconomy.org/stl/",
                "https://atyourservice.seattle.gov/2022/02/25/2022-hygiene-shower-trailer-  locations/",
                "https://solid-ground.org/get-help",
                "https://solid-ground.org/get-help/transportation",
                "https://sophiaway.org",
                "https://sound.health",
                "https://swyfs.org",
                "https://swedish.org",
                "https://teenfeed.org",
                "https://ccsww.org/get-help/housing/permanent-housing",
                "https://tukwilapantry.org",
                "https://uheightscenter.org",
                "https://valleycities.org",
                "https://valleycities.org",
                "https://kingcounty.gov/en/dept/dph/health-safety/health-centers-programs-  services/access-outreach-program/basic-food-program",
                "https://weldseattle.org",
                "https://worksourceskc.org/seattle",
                "https://ywcaworks.org/locations/willows",
                "https://www.hopelink.org",
                "https://www.issaquahcommunityservices.org",
                "https://www.issaquahfoodbank.org",
                "https://www.jfsseattle.org",
                "https://www.miyfs.org",
                "https://www.muslim-housing.org",
                "https://bellevue.salvationarmy.org/eastside_bellevue_corps/social-services",
                "https://www.svdpseattle.org",
                "https://www.issaquahfoodbank.org",
                "https://www.crisisconnections.org/king-county-2-1-1",
                "https://www.redcross.org",
                "https://www.bellevuewa.gov/city-government/departments/fire/emergency-management",
                "https://www.bothellwa.gov/314/Emergency-Preparedness",
                "https://www.kingcounty.gov/depts/emergency-management/alert-king-county",
                "https://www.kirklandwa.gov/Government/Departments/Fire-Department/Emergency-Management",
                "https://www.pse.com",
                "https://www.redmond.gov/512/Emergency-Management",
                "https://www.deathwithdignity.org",
                "https://www.evergreenhealth.com/hospice-care",
                "https://www.evergreenhealth.com/palliative-care",
                "https://www.hospicefoundation.org",
                "https://healthy.kaiserpermanente.org/washington/get-care/additional-services/hospice",
                "https://curohealthservices.com/locations/gentiva-hospice-seattle/",
                "https://www.klinegalland.org/care-options/community-based-services/hospice-care/",
                "https://www.overlakehospital.org/services/palliative-care",
                "https://www.providence.org/locations/wa/hospice-of-seattle",
                "https://www.evergreenhealth.com",
                "https://www.overlakehospital.org",
                "https://www.snoqualmiehospital.org",
                "https://www.swedish.org",
                "https://www.lcnw.org",
                "https://www.evergreenhealth.com/grief",
                "https://www.providence.org/locations/wa/hospice-of-seattle/grief-support-services",
                "https://www.kcwics.org",
                "https://www.bartonfuneral.com",
                "https://www.cascadememorial.com",
                "https://www.dignitymemorial.com/funeral-homes/redmond-wa/cedar-lawns-funeral-home/4422",
                "https://chapel.cedarpark.org",
                "https://www.funerals.coop",
                "https://www.elementalnw.com",
                "https://www.flintofts.com",
                "https://www.funeralandcremationcare.com",
                "https://www.dignitymemorial.com/funeral-homes/washelli",
                "https://mapsredmond.org/",
                "https://www.neptunesociety.com/location/seattle-cremation",
                "https://www.peoplesmemorial.org",
                "https://www.sunsethillsfuneralhome.com",
                "https://www.agingkingcounty.org/what-we-do/healthy-aging/",
                "https://www.dshs.wa.gov/esa/community-services-offices/basic-food",
                "https://ccsww.org/get-help/shelter-homeless-services/issaquah-meals/",
                "https://r2c2blog.wordpress.com/ministry/foodbank/",
                "https://cpkenmore.com/food-bank",
                "https://www.fallcityfoodpantry.org",
                "https://www.helpsnovalley.org",
                "https://www.issaquahfoodbank.org",
                "https://www.miyfs.org",
                "https://renewalfoodbank.org/",
                "https://www.snoqualmievalleyfoodbank.org",
                "https://www.woodinvillestorehouse.org",
                "https://www.northshoreseniorcenter.org",
                "https://www.issaquahwa.gov/seniors",
                "https://www.kirklandwa.gov/depart/parks/About_Parks_and_Community_Services/Senior_Services/Daily_Activity_Schedule",
                "https://www.mcsc.org/lunch",
                "https://www.mtsiseniorcenter.org",
                "https://www.redmond.gov/206/Redmond-Senior-Center",
                "https://www.lifelong.org/food-nutrition",
                "https://carnationfarmersmarket.org",
                "https://crossroadsbellevue.com/farmersmarket",
                "https://kirklandmarket.org",
                "https://www.sammamishfarmersmarket.org",
                "https://www.bellevuefarmersmarket.org",
                "https://duvallfarmersmarket.org/",
                "https://www.siviewpark.org/farmers-market.phtml",
                "https://www.kirklandwa.gov/Government/Departments/Parks-and-Community-Services/Special-Event-Services/Juanita-Friday-Market",
                "https://www.ci.issaquah.wa.us/market",
                "https://www.woodinvillefarmersmarket.com",
                "https://www.thirdplacecommons.org/farmers-market/",
                "https://www.mifarmersmarket.org",
                "https://www.napca.org",
                "https://www.benefitscheckup.org",
                "https://www.washingtonlawhelp.org/issues/aging-elder-law",
                "https://www.ichs.com/locations/ichs-legacy-house",
                "https://www.medicare.gov",
                "https://www.ssa.gov",
                "https://www.benefits.va.gov/seattle",
                "https://www.pugetsound.va.gov",
                "https://www.dshs.wa.gov",
                "https://www.dshs.wa.gov/altsa",
                "https://www.dshs.wa.gov/location/dshs-cso-040",
                "https://www.dshs.wa.gov",
                "https://www.dshs.wa.gov",
                "https://www.alanoclubeastside.org/",
                "https://www.adhl.org/",
                "https://eastsideaa.org/",
                "https://www.cascadebh.com",
                "https://consejocounseling.org/",
                "https://www.fairfaxhospital.com/programs/adults/",
                "https://www.hotelcaliforniabythesea.com/washington/",
                "https://kingcounty.gov/depts/community-human-services/mental-health-substance-abuse.aspx",
                "https://www.lakesidemilam.com",
                "https://www.seattlena.org",
                "https://www.nlrsnow.com",
                "https://www.providence.org",
                "https://www.ths-wa.org",
                "https://www.alz.org/alzwa",
                "https://www.alz.org/alzwa/helping_you/espanol",
                "https://www.communitylivingconnections.org/wp-content/uploads/sites/173/2023/01/Support-Group-List-King-County-January-2023-1.pdf",
                "https://www.momentiaseattle.org",
                "https://www.oldfriendsclub.org",
                "https://webwa.alsa.org/site/PageServer?pagename=WA_homepage",
                "https://www.arthritis.org/local-offices/wa-seattle",
                "https://www.cancer.org/about-us/local/washington",
                "https://www.cancercare.org",
                "https://www.cancerlifeline.org",
                "https://www.cancerpathways.org",
                "https://www.evergreenhealth.com/health-services/cancer-care",
                "https://www.cancer.gov",
                "https://www.overlakehospital.org/cancer",
                "https://www.diabetes.org/tools-support/diabetes-education-program",
                "https://www.evergreenhealth.com/health-services/diabetes-education-nutrition/",
                "https://www.overlakehospital.org/services/diabetes-endocrinology/diabetes-education-services",
                "https://www.communitylivingconnections.org",
                "https://www.lcsnw.org",
                "https://www.epilepsy.com/local/washington",
                "https://www.neuro-spine-ortho.com/health-services/neuroscience-spine-orthopedic-institute/",
                "https://www.biawa.org",
                "https://www.evergreenhealth.com/locations/locations-profile/?id=4",
                "https://www.heart.org/en/affiliates/washington/puget-sound",
                "https://www.evergreenhealth.com/heart",
                "https://www.overlakehospital.org/services/heart-vascular-care",
                "https://www.virginiamason.org/cardiology",
                "https://www.hepeducation.org",
                "https://www.gaycity.org",
                "https://www.lifelong.org",
                "https://doh.wa.gov/you-and-your-family/illness-and-disease-z/hiv/hiv-care-client-services",
                "https://www.kingcounty.gov/cd",
                "https://www.lung.org/",
                "https://www.evergreenhealth.com/ms",
                "https://www.mda.org/",
                "https://www.apdaparkinson.org/community/northwest/",
                "https://www.evergreenhealth.com/parkinsons",
                "https://www.yogaforpd.com",
                "https://www.evergreenhealth.com/sleep-disorder-services",
                "https://www.overlakehospital.org/services/sleep-medicine",
                "https://www.vmfh.org/our-services/sleep-disorders-center",
                "https://www.heart.org/en/affiliates/washington/puget-sound",
                "https://www.evergreenhealth.com/stroke",
                "https://www.evergreenhealth.com/stroke-support-group",
                "https://www.stroke.org/en/help-and-support/for-family-caregivers/stroke-family-warmline",
                "https://www.kingcounty.gov/eastgate",
                "https://www.healthpointchc.org/health-centers/redmond",
                "https://www.ichs.com/bellevue",
                "https://www.mapsredmond.org/mcrc-health-clinic",
                "https://www.seamar.org",
                "https://www.drtomseal.com",
                "https://www.enabledental.com",
                "https://www.lwtech.edu/campus-life/dental-clinic",
                "https://www.skcds.org",
                "https://www.dental.washington.edu/patient",
                "https://www.captioncall.com",
                "https://soundgenerations.org/",
                "https://www.eastsideaudiology.com",
                "https://www.everhear.com",
                "https://www.evergreenhealth.com/speech-therapy-program",
                "https://www.hearingspecialtycenter.com",
                "https://www.hsdc.org",
                "https://www.overlakehospital.org/services/rehabilitation-care/speech-therapy",
                "https://www.deltadentalwa.com",
                "https://www.evergreenhealth.com/healthline",
                "https://www.insurance.wa.gov/statewide-health-insurance-benefits-advisors-shiba",
                "https://www.hca.wa.gov/free-or-low-cost-health-care/i-need-medical-dental-or-vision-care",
                "https://www.wahealthplanfinder.org",
                "https://www.apria.com/shop",
                "https://www.bellevuehealthcare.com",
                "https://bridgemin.org/medical-equipment",
                "https://www.mdmedicalsupplies.com",
                "https://www.rotech.com",
                "https://www.evergreenhealth.com/geriatric-medicine",
                "https://www.overlakehospital.org/services/senior-health",
                "https://www.dsb.wa.gov",
                "https://www.wtbbl.org",
                "https://www.zoomcare.com/clinic/zoomcare-bellevue-4th",
                "https://www.zoomcare.com/clinic/zoomcare-bothell",
                "https://www.overlakehospital.org/department/urgent-care",
                "https://www.zoomcare.com/clinic/zoomcare-overlake",
                "https://www.evergreenhealth.com/urgent-care",
                "https://www.carepointonline.org",
                "https://www.zoomcare.com/clinic/zoomcare-woodinville",
                "https://www.agingwisdom.com",
                "https://caremanagers-nw.com/",
                "https://www.fulllifecare.org",
                "https://www.jfsseattle.org",
                "https://www.mercerisland.gov/yfs/page/senior-services",
                "https://www.eastsidefriendsofseniors.org",
                "https://www.fulllifecare.org/we-can-help/by-service/elderfriends",
                "https://americorps.gov/serve/americorps-seniors",
                "https://www.medicalert.org/alz",
                "https://www.medicalert.org",
                "https://www.smart911.com",
                "https://www.bayalarmmedical.com",
                "https://www.greatcall.com",
                "https://www.lifealert.com",
                "https://www.lifestation.com/lp1-medical-alert/?conid=169",
                "https://www.medicalalert.com",
                "https://www.medicalguardian.com",
                "https://www.mobilehelp.com",
                "https://www.lifeline.com/",
                "https://www.rescuealert.com",
                "https://www.amicablehealth.net",
                "https://www.andelcare.com",
                "https://www.companioncareofwa.com",
                "https://www.familyresourcehomecare.com/locations/bellevue/",
                "https://www.fedeltahomecare.com",
                "https://www.griswoldhomecare.com/bellevue-eastside/",
                "https://www.homeinstead.com",
                "https://www.homewatchcaregivers.com/bellevue/",
                "https://kinon.org/",
                "https://www.klinegalland.org/care-options/community-based-services/home-health/",
                "https://www.kwacares.org/our-services/in-home-care/",
                "https://www.carelinx.com/optimal-aging",
                "https://synergyhomecare.com/",
                "https://www.visitingangels.com/assisted-senior-care-kirkland-washington-98034_1148",
                "https://www.careagehealth.com",
                "https://www.evergreenhealth.com/health-services/home-care/",
                "https://www.centerwellhomehealth.com/",
                "https://washington.providence.org/locations-directory/h/home-services-king-county",
                "https://www.ccsww.org",
                "https://www.bellevuewa.gov/city-government/departments/parks/community-services/human-services/home-repair-assistance",
                "https://kingcounty.gov/depts/community-human-services/housing/services/housing-repair.aspx",
                "https://www.kcha.org/wx",
                "https://www.mbaks.com/community/rampathon",
                "https://www.northshoreseniorcenter.org",
                "https://www.rebuildingtogethereastside.org/",
                "https://www.harmonycaresmedicalgroup.com",
                "https://www.crisisconnections.org/get-help/resources/older-adult-support",
                "https://www.fulllifecare.org/services/adult-day-health-care/",
                "https://www.lifespanrespitewa.org/respite-care/adults-elders",
                "https://www.crisisconnections.org/king-county-2-1-1",
                "https://www.acrs.org",
                "https://www.kcha.org/housing/property.aspx?PropertyID=120",
                "https://www.providence.org/supportive-housing/find-a-place-to-live/providence-john-gabriel-house",
                "https://www.housing4seniors.com/communities/east-side/bellevue/crossroads-senior-living-privte",
                "https://www.livewoodlandsatforbeslakeapartments.com/",
                "https://www.crisisconnections.org/king-county-2-1-1",
                "https://www.acrs.org",
                "https://www.bellevuewa.gov/mini-city-hall",
                "https://www.cisc-seattle.org",
                "https://www.communitylivingconnections.org",
                "https://www.dshs.wa.gov/esa/community-services-offices/community-services-office",
                "https://www.eastafricancs.org/",
                "https://www.evergreenhealthcare.org/access",
                "https://www.gaycity.org",
                "https://www.jfsseattle.org/refugee",
                "https://www.aarp.org/wa",
                "https://www.disabilityrightswa.org",
                "https://www.waombudsman.org",
                "https://www.waseniorlobby.org",
                "https://washington.retiredamericans.org/",
                "https://www.aarp.org/money/scams-fraud",
                "https://www.identitytheft.gov",
                "https://www.atg.wa.gov/fraud-fighters#:~:text=If%20you%20have%20questions%2C%20or,%2D877%2D908%2D3360.",
                "https://www.dshs.wa.gov/altsa",
                "https://www.uwmedicine.org/locations/harborview-abuse-and-trauma-center",
                "https://www.dvhopeline.org",
                "https://www.victimsupportservices.org",
                "https://www.waombudsman.org",
                "https://www.joincake.com",
                "https://www.nwjustice.org/home",
                "https://www.nwjustice.org/get-legal-help",
                "https://www.elap.org",
                "https://www.kcba.org/For-the-Public/Free-Legal-Assistance",
                "https://www.crisisconnections.org",
                "https://kingcounty.gov/depts/community-human-services/mental-health-substance-abuse/services/crisis-services.aspx",
                "https://www.sound.health",
                "https://www.obhadvocacy.org/",
                "https://www.evergreenhealth.com/in-home-behavioral-health",
                "https://www.herohousenw.org",
                "https://www.acrs.org",
                "https://www.consejocounseling.org",
                "https://www.jfsseattle.org",
                "https://www.wellspringfs.org",
                "https://www.cascadebh.com",
                "https://www.fairfaxhospital.com",
                "https://www.uwmedicine.org/locations/inpatient-psychiatry-harborview",
                "https://www.uwmedicine.org/locations/adult-psychiatry-uwmc-northwest-seattle",
                "https://www.overlakehospital.org/services/mental-behavioral-health/outpatient-psychiatry",
                "https://www.uwmedicine.org/locations/psychiatry-outpatient-uwmc-roosevelt",
                "https://www.myfinancialgoals.org/",
                "https://www.consumerfinance.gov/older-americans",
                "https://www.hopelink.org/need-help/financial-capabilities",
                "https://www.northshoreseniorcenter.org",
                "https://www.seniormoneyproject.org",
                "https://www.aarp.org/money/taxes/aarp_taxaide/",
                "https://www.uwkc.org/need-help/tax-help",
                "https://www.bothellwa.gov/1320/Low-income-senior-discount-program",
                "https://www.carnationwa.gov/utility-billing/",
                "https://www.duvallwa.gov/132/Utility-Billing",
                "https://www.ci.issaquah.wa.us/index.aspx?NID=297",
                "https://www.kirklandwa.gov/depart/Finance_and_Administration/communityservices/Utility_Billing.htm",
                "https://www.mercerisland.gov/finance/page/utilities-service-discounts",
                "https://www.redmond.gov/449/Utilities",
                "https://www.nesswd.org",
                "https://www.ci.snoqualmie.wa.us/130/Water-Services",
                "https://www.woodinvillewater.com/131/Pay-My-Bill",
                "https://www.nud.net/my-account/payment-information/low-income-discount-program",
                "https://www.hopelink.org/need-help/energy",
                "https://www.kingcounty.gov/depts/assessor/TaxRelief.aspx",
                "https://www.homewardpet.org",
                "https://www.imaginepeaceforpupsrescue.com/",
                "https://www.meowcatrescue.org",
                "https://www.motleyzooanimalrescue.org",
                "https://www.pupdogrescue.org",
                "https://www.kingcounty.gov/depts/regional-animal-services.aspx",
                "https://www.RescueUnleashed.org",
                "https://www.seattlehumane.org",
                "https://www.spdrdogs.org",
                "https://www.washingtonferret.org",
                "https://www.medina-wa.gov/centralservices/webform/animal-licensing",
                "https://www.kirklandwa.gov/depart/PD/Community_Resources/Animal_Services",
                "https://www.CompanionAnimalSolutions.com",
                "https://www.drtinavet.com",
                "https://www.housepetvetvisits.com",
                "https://www.homewardpet.org",
                "https://www.northshoreseniorcenter.org",
                "https://www.seattlehumane.org",
                "https://www.kcls.org/older-adults",
                "https://www.kcls.org/locations/crossroads",
                "https://www.kcls.org/locations/Bellevue",
                "https://www.kcls.org/locations/Newport",
                "https://www.kcls.org/locations/Bothell",
                "https://www.kcls.org/locations/Carnation",
                "https://www.kcls.org/locations/Duvall",
                "https://kcls.org/locations/fall-city/",
                "https://www.kcls.org/locations/Issaquah",
                "https://www.kcls.org/locations/Kenmore",
                "https://kcls.org/locations/kirkland/",
                "https://www.kcls.org/locations/Kingsgate",
                "https://www.kcls.org/locations/Mercer Island",
                "https://www.kcls.org/locations/Newcastle",
                "https://www.kcls.org/locations/North Bend",
                "https://www.kcls.org/locations/Redmond",
                "https://www.kcls.org/locations/Sammamish",
                "https://www.kcls.org/locations/Snoqualmie",
                "https://www.kcls.org/locations/Woodinville",
                "https://www.bellevuecollege.edu/ce/retiree-programs",
                "https://www.bellevuewa.gov/city-government/departments/parks/sports-and-athletics/bellevue-aquatic-center",
                "https://www.bellevuewa.gov/crossroads",
                "https://bellevuewa.gov/city-government/departments/parks/community-centers/highland",
                "https://bellevuewa.gov/city-government/departments/parks/community-centers/north-bellevue-community-center",
                "https://bellevuewa.gov/city-government/departments/parks/community-centers/sbcc",
                "https://www.issaquahwa.gov/",
                "https://www.issaquahwa.gov/seniors",
                "https://www.issaquahwa.gov/",
                "https://www.kirklandwa.gov/Government/Departments/Parks-and-Community-Services/Register-for-a-R",
                "https://www.kirklandwa.gov/pool",
                "https://www.mercerislandpool.com",
                "https://www.mercerisland.gov/parksrec/",
                "https://www.mtsiseniorcenter.org/",
                "https://www.northshoreseniorcenter.org",
                "https://www.kenmorewa.gov/our-city/recreation/life-long-recreation",
                "https://www.redmond.gov/communitycenter",
                "https://www.redmond.gov/206/Senior-Services-and-Resources",
                "https://www.siviewpark.org",
                "https://www.mtsiseniorcenter.org",
                "https://www.silversneakers.com",
                "https://www.sjcc.org",
                "https://www.waveaquatics.org.",
                "https://www.redmond.gov/407/The-Redmond-Pool",
                "https://www.seattleymca.org/locations/bellevue-family-ymca",
                "https://www.seattleymca.org/locations/coal-creek-family-ymca",
                "https://www.seattleymca.org/locations/northshore-ymca",
                "https://www.seattleymca.org/locations/sammamish-community-ymca",
                "https://www.filcommsea.org",
                "https://www.idicseniorcenter.org",
                "https://www.iacswa.org",
                "https://www.mature-friends.org/#/",
                "https://www.sihb.org",
                "https://www.sjcc.org",
                "https://www.cisc-seattle.org/programs/",
                "https://unitedindians.org/services/elders-program/",
                "https://local.aarp.org/seattle-wa/about-aarp",
                "https://www.nurturingwatertherapies.org",
                "https://www.aarp.org/benefits-discounts/all/driver-safety/",
                "https://www.cancer.org/treatment/support-programs-and-services/patient-transportation.html",
                "https://kingcounty.gov/depts/transportation/metro/fares-orca/transit-go-ticket.aspx",
                "https://www.eastsidefriendsofseniors.org",
                "https://www.hopelink.org/need-help/transportation/medicaid-transportation",
                "https://www.kingcounty.gov/depts/transportation/metro/travel-options/accessible/programs/access-transportation.aspx",
                "https://kingcounty.gov/depts/transportation/metro/travel-options/accessible/programs/paratransit.aspx",
                "https://www.crisisconnections.org/rideunite",
                "https://www.svtbus.org",
                "https://www.findaride.org",
                "https://www.kingcounty.gov/depts/transportation/metro/travel-options/bus.aspx",
                "https://www.kingcounty.gov/depts/transportation/metro/travel-options/accessible/programs/accessible-bus/transit-instruction.aspx",
                "https://www.kingcounty.gov/depts/transportation/metro/fares-orca/orca-cards/reduced-fare-permit.aspx",
                "https://kingcounty.gov/depts/transportation/metro/travel-options/accessible/programs/taxi-scrip.aspx",
                "https://www.alpinelicensing.com",
                "https://www.tabs4u.com",
                "https://www.eastsideautolicensing.com",
                "https://www.woodinvillelicense.com",
                "https://www.worthingtonlicensing.com",
                "https://www.legion.org",
                "https://www.post161.org",
                "https://www.compasshousingalliance.org/veterans-programs/",
                "https://www.va.gov/pension/aid-attendance-housebound",
                "https://www.benefits.va.gov/seattle/",
                "https://www.vfwmercerisland.org",
            "https://curohealthservices.com/locations/gentiva-hospice-seattle/",
            "https://curohealthservices.com/locations/gentiva-hospice-seattle/",
            "https://www.sikhcentreofseattle.org/Langar.aspx",
            "https://openkitchenredmond.com/",
            "https://www.sikhcentreofseattle.org/Langar.aspx",
            "https://www.sikhcentreofseattle.org/Langar.aspx/",
            "https://openkitchenredmond.com/" ,
            "www.oldfriendsclub.org",
            "https://app.leg.wa.gov/districtfinder",
            "https://app.leg.wa.gov/districtfinder",
            "https://signaturehch.com/",
            "https://soundgenerations.org/our-programs/minor-home-repair/",
            "https://soundgenerations.org/our-programs/senior-rights-assistance/",
            "https://soundgenerations.org/our-programs/grat/",
            "https://carnationwa.govoffice2.com/vertical/sites/%7BBC2C8B0D-6FDD-43CB-A5E7-03E465DF30E5%7D/uploads/Utility_Account_Application_-_FILLABLE.pdf?&pri=0",
            "https://soundgenerations.org/our-programs/transportation/hyde-shuttle/",
            "https://wa.kaiserpermanente.org/html/public/specialties/cardiology",
            "https://hearingloss-wa.org/what-we-do/hope-hearing-other-peoples-experiences/",
            "https://sphsc.washington.edu/apply-services",
            "https://curohealthservices.com/locations/gentiva-hospice-seattle/",
            "https://www.legacyhouse.org",
            "https://www.soundgenerations.org",
            "https://bikeworks.org/bikes-for-all",
            "https://desc.org/what-we-do/survival-services/",
            "https://soundgenerations.org/our-programs/transportation/hyde-shuttle/",
            "https://newbegin.org",
            "https://www.mercergov.org/emergencymanagement",
            "https://www.endoflifewa.org",
            "https://www.snovalleysenior.org/services/food-and-dining",
            "https://www.soundgenerations.org/meals-on-wheels",
            "https://www.recoverycentermonroe.com",
            "https://www.endbraincancer.org",
            "https://www.seattlecca.org",
            "https://www.nwpf.org",
            "https://www.uwmedicine.org/locations/primary-care-issaquah",
            "https://www.ftfa.org",
            "https://www.alliancenursing.com",
            "https://www.kingcd.org/programs/better-soils/healthy-soil",
            "https://www.hcaw.org",
            "https://www.pic.org/care-management.htm",
            "https://www.lifewire.org",
            "https://www.pic.org",
            "https://www.nami-eastside.org",
            "https://www.svpetfoodbank.org",
            "https://www.elcentrodelaraza.org",
            "https://www.uccwa.us",
            "https://www.soundgenerations.org",
            "https://soundgenerations.org/our-programs/food-security/meals-on-wheels/"
    };

    public static final String[] BAD_URLS = {
            "https://ccsww.org/get-help/services-for-seniors-people-with-disabilities/volunteer-services/volunteer-services-king-county/",
            "https://elderoptionswa.com/safe%40home-1",
            "https://ccsww.org/get-help/services-for-seniors-people-with-disabilities/home-care/",
            "https://www.www.pugetsoundlaboragency.org/wheelchair-ramp-program.html",
            "https://www.www.pic.org/care-management.htm",
            "https://ccsww.org/get-help/services-for-seniors-people-with-disabilities/african-american-elders-program/",
            "https://consejocounseling.org/portfolio/valve-diseases/",
            "https://www.www.lni.wa.gov/claims/crime-victim-claims/who-can-file-and-what-is-covered/",
            "https://www.www.lifewire.org/get-help/legal-support/",
            "https://forms.gle/qNr8P9Cvhzq6w66k9).",
            "https://soundgenerations.org/get-help/insurance-legal/your-rights/",
            "https://www.www.4tomorrow.today/programs",
            "https://www.elcentrodelaraza.org/what-we-do/education-and-asset-building",
            "https://www.www.wholecatandkaboodle.com/adoptions",
            "https://www.www.kirklandwa.gov/Government/Departments/Parks-and-Community-Services/Register-for-a-R",
            "https://www.www.redmond.gov/409/Art-Studio-at-Grass-Lawn-Park",
            "https://ccsww.org/get-help/services-for-seniors-people-with-disabilities/volunteer-services/volunteer-services-king-county/",
            "https://snofallslicensing.com/",
            "https://vets.force.com/VAVERA/s/.",
            "https://wsdot.wa.gov/travel/511-travel-information",
            "https://www.www.hopelink.org/need-help/mobile-market",
            "https://www.www.lifelong.org/welcome-home",
            "https://www.motivationsrecoverycenter.com/",
            "https://confidentialstdtestingcenters-stdtestingservice.business.site/",
            "https://website-593855303609607720976-stdtestingservice.business.site",
            "https://sasgcc.org/support",
            "https://evergreenhealth.healthlines.org/wlp2/#!/classes/search",
             "https://usmission.org Hours |",
            "https://www.ccsww.org/get-help/shelter-homeless-services/emergency-assistance",
            "https://www.legacyadvisor.com",
            "https://www.asacredmoment.com",
            "https://www.hopelink.org/get_help/food",
            "https://www.hopelink.org/need-help/mobile-market",
            "https://www.lifelong.org/welcome-home",
            "https://www.redmondSatmarket.org",
            "https://www.motivationsrecoverycenter.com/",
              "https://www.nationalmssociety.org/Chapters/WAS",
            "https://www.bellevuerotacare.org",
            "https://www.nwadacenter.org",
            "https://www.snoqualmiehospital.org/clinics/outpatient-therapy",
             "https://www.pugetsoundlaboragency.org/wheelchair-ramp-program.html",
            "https://www.watap.org",
            "https://www.lni.wa.gov/claims/crime-victim-claims/who-can-file-and-what-is-covered/",
            "https://www.lifewire.org/get-help/legal-support/",
            "https://www.ocva.wa.gov",
            "https://www.ccsww.org/get-help/specialized-services/tenant-law-center",
             "https://www.callblackline.org",
            "https://www.suicidepreventionlifeline.org",
            "https://www.4tomorrow.today/programs",
            "https://www.elcentrodelaraza.org/what-we-do/education-and-asset-building",
              "https://www.bellevuewa.gov/city-government/departments/utilities/pay-your-utility-bill/utility-rate-and-tax-relief",
            "https://www.northbendwa.gov/index.aspx?NID=69",
            "https://www.wholecatandkaboodle.com/adoptions",
            "https://www.ci.bothell.wa.us/283/Animal-Services",
            "https://www.homepetvet.com",
            "https://www.kraftmobilevet.com",
            "https://www.mobilevetseattle.com",
            "https://www.hope-link.org",
                 "https://www.redmond.gov/409/Art-Studio-at-Grass-Lawn-Park",
            "https://www.waveaquatics.org/jac",
              "https://www.findaride.org/vet-transportation",

            "https://www.vfw3436.org",
            "https://www.vfwredmond.org",

    };
 
    public static Set<String> KnownBadURLS = new HashSet<>(); // Set.of(BAD_URLS);
    public static Set<String> KnownGoodURLS = new HashSet<>(); // Set.of(BAD_URLS);
    static {
        for (int i = 0; i < GOOD_URLS.length; i++) {
            KnownGoodURLS.add(GOOD_URLS[i]);
        }
        for (int i = 0; i < BAD_URLS.length; i++) {
            KnownBadURLS.add(BAD_URLS[i]);
        }
    }

    public static void main(String[] args) {
        String test = "https://openkitchenredmond.com/";
        boolean good = URLValidator.isValidURL(test);

        List<String>  Good = new ArrayList<>();
        List<String>  Bad = new ArrayList<>();

        for (int i = 0; i < BAD_URLS.length; i++) {
            String url = BAD_URLS[i];
  //          System.out.println(url);
            boolean valid = URLValidator.isValidURL(url,true);
            if(valid) {
                Good.add(url);
            }
            else {
                Bad.add(url);
            }
        }
        System.out.println("Bad Urls");
        for (String s : Bad) {
            System.out.println("\"" + s + "\",");
        }
    }
}
